import 'package:downvid/models/video_downloaded_model/video_downloaded_model.dart';
import 'package:downvid/objectbox.g.dart';
// ignore: depend_on_referenced_packages
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
// import 'objectbox.g.dart';

class ObjectBox {
  late Store store;

  ObjectBox._create(this.store) {
    // add any additional setup code here
  }

  /// Create an instance of ObjectBox to be used throughout the app
  static Future<ObjectBox> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    // Future<Store> openStore() {...} is defined in the generated objectbox.g.dart
    final store =
        await openStore(directory: p.join(docsDir.path, "obx-downvid"));
    print("OBJECT STORE CREATED: ${store.toString()}");
    return ObjectBox._create(store);
  }


  /// Fetch all downloaded videos from ObjectBox
  List<VideoDownloadedModel> getAllDownloadedVideos() {
    final box = store.box<VideoDownloadedModel>();
    final videos = box.getAll();
    return videos;
  }
}

// class DummyData {
//   static final List<VideoDownloadedModel> dummyVideos = [
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 1",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "2:30",
//       videoFileSize: "10MB",
//       videoPath: "path/to/video1.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video1",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 2",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "3:30",
//       videoFileSize: "20MB",
//       videoPath: "path/to/video2.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video2",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 3",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "4:30",
//       videoFileSize: "30MB",
//       videoPath: "path/to/video3.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video3",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 4",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "5:30",
//       videoFileSize: "40MB",
//       videoPath: "path/to/video4.mp4",
//       videoQuality: "1080p",
//       videoSocialUrl: "https://www.facebook.com/video4",
//       videoType: "mp4",
//     ),
//     VideoDownloadedModel(
//       title: "Video 5",
//       thumbnail: "https://via.placeholder.com/150",
//       videoDuration: "6:30",
//       videoFileSize: "50MB",
//       videoPath: "path/to/video5.mp4",
//       videoQuality: "720p",
//       videoSocialUrl: "https://www.facebook.com/video5",
//       videoType: "mp4",
//     ),
  // ];
// }
