name: downvid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  video_player: ^2.10.1
  fluttertoast: ^9.0.0
  path_provider: ^2.1.5
  get_it: ^9.1.1
  google_mobile_ads: ^6.0.0
  html: ^0.15.6
  http: ^1.6.0
  in_app_review: ^2.0.11
  intl: any
  receive_sharing_intent: ^1.8.1
  media_store_plus: ^0.1.3
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.2
  icons_launcher: ^3.0.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  sizer: ^3.1.3
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: ^2.10.4
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: 5.0.2

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/ad/
    - assets/flags/
    - assets/lottie/
