// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/video_downloaded_model/video_downloaded_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2038432172506542294),
    name: 'VideoDownloadedModel',
    lastPropertyId: const obx_int.IdUid(11, 6983346339509507642),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 305084158553770904),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6857390349834419088),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4047143724066093614),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3638050861309354703),
        name: 'videoSocialUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7009776888079897366),
        name: 'videoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6905307388448828602),
        name: 'videoType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7900331837309031785),
        name: 'videoQuality',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4587869781394870316),
        name: 'videoFileSize',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7035482258299803877),
        name: 'videoDuration',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2365999919602373148),
        name: 'videoDownloadedDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6983346339509507642),
        name: 'originalUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2038432172506542294),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    VideoDownloadedModel: obx_int.EntityDefinition<VideoDownloadedModel>(
      model: _entities[0],
      toOneRelations: (VideoDownloadedModel object) => [],
      toManyRelations: (VideoDownloadedModel object) => {},
      getId: (VideoDownloadedModel object) => object.id,
      setId: (VideoDownloadedModel object, int id) {
        object.id = id;
      },
      objectToFB: (VideoDownloadedModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final thumbnailOffset = fbb.writeString(object.thumbnail);
        final videoSocialUrlOffset = fbb.writeString(object.videoSocialUrl);
        final videoPathOffset = fbb.writeString(object.videoPath);
        final videoTypeOffset = fbb.writeString(object.videoType);
        final videoQualityOffset = fbb.writeString(object.videoQuality);
        final videoFileSizeOffset = fbb.writeString(object.videoFileSize);
        final videoDurationOffset = fbb.writeString(object.videoDuration);
        final originalUrlOffset = fbb.writeString(object.originalUrl);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, thumbnailOffset);
        fbb.addOffset(3, videoSocialUrlOffset);
        fbb.addOffset(4, videoPathOffset);
        fbb.addOffset(5, videoTypeOffset);
        fbb.addOffset(6, videoQualityOffset);
        fbb.addOffset(7, videoFileSizeOffset);
        fbb.addOffset(8, videoDurationOffset);
        fbb.addInt64(9, object.videoDownloadedDate.millisecondsSinceEpoch);
        fbb.addOffset(10, originalUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final videoSocialUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final videoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final videoTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final videoQualityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final videoFileSizeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final videoDurationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final videoDownloadedDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final originalUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = VideoDownloadedModel(
          id: idParam,
          title: titleParam,
          thumbnail: thumbnailParam,
          videoSocialUrl: videoSocialUrlParam,
          videoPath: videoPathParam,
          videoType: videoTypeParam,
          videoQuality: videoQualityParam,
          videoFileSize: videoFileSizeParam,
          videoDuration: videoDurationParam,
          videoDownloadedDate: videoDownloadedDateParam,
          originalUrl: originalUrlParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VideoDownloadedModel] entity fields to define ObjectBox queries.
class VideoDownloadedModel_ {
  /// See [VideoDownloadedModel.id].
  static final id = obx.QueryIntegerProperty<VideoDownloadedModel>(
    _entities[0].properties[0],
  );

  /// See [VideoDownloadedModel.title].
  static final title = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[1],
  );

  /// See [VideoDownloadedModel.thumbnail].
  static final thumbnail = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[2],
  );

  /// See [VideoDownloadedModel.videoSocialUrl].
  static final videoSocialUrl = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[3],
  );

  /// See [VideoDownloadedModel.videoPath].
  static final videoPath = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[4],
  );

  /// See [VideoDownloadedModel.videoType].
  static final videoType = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[5],
  );

  /// See [VideoDownloadedModel.videoQuality].
  static final videoQuality = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[6],
  );

  /// See [VideoDownloadedModel.videoFileSize].
  static final videoFileSize = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[7],
  );

  /// See [VideoDownloadedModel.videoDuration].
  static final videoDuration = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[8],
  );

  /// See [VideoDownloadedModel.videoDownloadedDate].
  static final videoDownloadedDate =
      obx.QueryDateProperty<VideoDownloadedModel>(_entities[0].properties[9]);

  /// See [VideoDownloadedModel.originalUrl].
  static final originalUrl = obx.QueryStringProperty<VideoDownloadedModel>(
    _entities[0].properties[10],
  );
}
